/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.AsistenciaController;
import java.util.Date;
import javax.swing.JOptionPane;
import modelo.Asistencia;
import modelo.Usuario;
import java.time.LocalTime;
import java.sql.Time;
import java.util.Date;

/**
 *
 * @author yorda
 */
public class TrabajadorHome extends javax.swing.JFrame {
    private Usuario usuario;
   
    public TrabajadorHome(Usuario usuario) {
          this.usuario = usuario;
        initComponents();
        setLocationRelativeTo(null);
    }

private void registrarIngreso() {
    // Obtener la fecha y hora actuales
    Date fechaActual = new Date(); // Obtiene la fecha actual
    LocalTime horaActual = LocalTime.now(); // Obtiene la hora actual

    // Crear una instancia de Asistencia con los datos necesarios
    Asistencia asistencia = new Asistencia();
    asistencia.setIdUsuario(usuario.getIdUsuario());
    asistencia.setFecha(fechaActual);
    asistencia.setHoraEntrada(Time.valueOf(horaActual)); // Convierte LocalTime a Time

    // Registrar la asistencia a través del controlador
    AsistenciaController asistenciaController = new AsistenciaController();
    boolean exito = asistenciaController.registrarAsistencia(asistencia);

    // Mostrar un mensaje dependiendo del resultado
    if (exito) {
        JOptionPane.showMessageDialog(this, "Asistencia registrada exitosamente.");
    } else {
        JOptionPane.showMessageDialog(this, "Error al registrar la asistencia.");
    }
}
private void registrarSalida() {
    // Obtener la fecha y hora actuales
    Date fechaActual = new Date(); // Obtiene la fecha actual
    LocalTime horaActual = LocalTime.now(); // Obtiene la hora actual

    // Crear una instancia de Asistencia con los datos necesarios
    Asistencia asistencia = new Asistencia();
    asistencia.setIdUsuario(usuario.getIdUsuario());
    asistencia.setFecha(fechaActual);
    asistencia.setHoraSalida(Time.valueOf(horaActual)); // Convierte LocalTime a Time

    // Registrar la salida a través del controlador
    AsistenciaController asistenciaController = new AsistenciaController();
    boolean exito = asistenciaController.registrarSalida(asistencia);

    // Mostrar un mensaje dependiendo del resultado
    if (exito) {
        JOptionPane.showMessageDialog(this, "Salida registrada exitosamente.");
    } else {
        JOptionPane.showMessageDialog(this, "Error al registrar la salida.");
    }
}




    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnregistraringreso = new javax.swing.JButton();
        btnregistrarsalida = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Bienvenido a tu Asistencia virtual");

        btnregistraringreso.setText("Registrar Ingreso");
        btnregistraringreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregistraringresoActionPerformed(evt);
            }
        });

        btnregistrarsalida.setText("Registrar Salida");
        btnregistrarsalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregistrarsalidaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(417, 417, 417)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                    .addComponent(btnregistraringreso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnregistrarsalida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(516, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(btnregistraringreso)
                .addGap(45, 45, 45)
                .addComponent(btnregistrarsalida)
                .addContainerGap(397, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnregistraringresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregistraringresoActionPerformed
      registrarIngreso();
    }//GEN-LAST:event_btnregistraringresoActionPerformed

    private void btnregistrarsalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregistrarsalidaActionPerformed
        registrarSalida();
    }//GEN-LAST:event_btnregistrarsalidaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TrabajadorHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TrabajadorHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TrabajadorHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TrabajadorHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnregistraringreso;
    private javax.swing.JButton btnregistrarsalida;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
